disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - vertical_whitespace
  - todo
  - identifier_name
  - weak_delegate
  - class_delegate_protocol

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage

variable_name:
  excluded: # excluded via string array
    - id
    - on
    
file_length:
  warning: 550
  error: 800

type_body_length:
  - 300 # warning