disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - conditional_binding_cascade
  - todo
  - vertical_whitespace
  - cyclomatic_complexity
  - function_body_length
  - legacy_constructor
  - for_where

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage

variable_name:
  excluded: # excluded via string array
    - id
    - on
