/*
LocalizableConstants.swift

GENERATED - DO NOT MODIFY - use localio instead.

Created by localio
*/

import Foundation


let kLocaleOrcGlobalCancelButton: String = { return localize("orc_global_cancel_button", comment: "") }()
let kLocaleOrcGlobalOkButton: String = { return localize("orc_global_ok_button", comment: "") }()
let kLocaleOrcGlobalOkUppercasedButton: String = { return localize("orc_global_ok_uppercased_button", comment: "") }()
let kLocaleOrcGlobalSettingsButton: String = { return localize("orc_global_settings_button", comment: "") }()
let kLocaleOrcLocationServiceOffAlertTitle: String = { return localize("orc_location_service_off_alert_title", comment: "") }()
let kLocaleOrcBackgroundLocationOffAlertTitle: String = { return localize("orc_background_location_off_alert_title", comment: "") }()
let kLocaleOrcBackgroundLocationAlertMessage: String = { return localize("orc_background_location_alert_message", comment: "") }()
let kLocaleOrcDefaultLocalNotificationTitle: String = { return localize("orc_default_local_notification_title", comment: "") }()
let kLocaleOrcDefaultLocalNotificationMessage: String = { return localize("orc_default_local_notification_message", comment: "") }()
let kLocaleOrcScannerTitle: String = { return localize("orc_scanner_title", comment: "") }()
let kLocaleOrcScanningMessage: String = { return localize("orc_scanning_message", comment: "") }()
let kLocaleOrcMatchNotFoundMessage: String = { return localize("orc_match_not_found_message", comment: "") }()
let kLocaleOrcMatchFoundMessage: String = { return localize("orc_match_found_message", comment: "") }()
let kLocaleOrcCameraPermissionOffTitle: String = { return localize("orc_camera_permission_off_title", comment: "") }()
let kLocaleOrcCameraPermissionOffMessage: String = { return localize("orc_camera_permission_off_message", comment: "") }()
let kLocaleOrcBrowserTitle: String = { return localize("orc_browser_title", comment: "") }()
let kLocaleOrcUnexpectedError: String = { return localize("orc_unexpected_error", comment: "") }()
let kLocaleOrcVuforiaTitle: String = { return localize("orc_vuforia_title", comment: "") }()
let kLocaleOrcVuforiaButtonStart: String = { return localize("orc_vuforia_button_start", comment: "") }()
let kLocaleOrcVuforiaActivitiesListTitle: String = { return localize("orc_vuforia_activities_list_title", comment: "") }()
let kLocaleOrcVuforiaActivitiesListEmpty: String = { return localize("orc_vuforia_activities_list_empty", comment: "") }()
let kLocaleOrcVuforiaButtonOk: String = { return localize("orc_vuforia_button_ok", comment: "") }()
let kLocaleOrcVuforiaContentDescCameraButton: String = { return localize("orc_vuforia_content_desc_camera_button", comment: "") }()
let kLocaleOrcVuforiaOverlayBuildTargetHelp: String = { return localize("orc_vuforia_overlay_build_target_help", comment: "") }()
let kLocaleOrcVuforiaTargetQualityErrorTitle: String = { return localize("orc_vuforia_target_quality_error_title", comment: "") }()
let kLocaleOrcVuforiaTargetQualityErrorDesc: String = { return localize("orc_vuforia_target_quality_error_desc", comment: "") }()
let kLocaleOrcVuforiaMenuBack: String = { return localize("orc_vuforia_menu_back", comment: "") }()
let kLocaleOrcVuforiaMenuExtendedTracking: String = { return localize("orc_vuforia_menu_extended_tracking", comment: "") }()
let kLocaleOrcVuforiaMenuCharacterMode: String = { return localize("orc_vuforia_menu_character_mode", comment: "") }()
let kLocaleOrcVuforiaMenuFlash: String = { return localize("orc_vuforia_menu_flash", comment: "") }()
let kLocaleOrcVuforiaMenuFlashErrorOn: String = { return localize("orc_vuforia_menu_flash_error_on", comment: "") }()
let kLocaleOrcVuforiaMenuFlashErrorOff: String = { return localize("orc_vuforia_menu_flash_error_off", comment: "") }()
let kLocaleOrcVuforiaMenuContautofocus: String = { return localize("orc_vuforia_menu_contautofocus", comment: "") }()
let kLocaleOrcVuforiaMenuContautofocusErrorOn: String = { return localize("orc_vuforia_menu_contautofocus_error_on", comment: "") }()
let kLocaleOrcVuforiaMenuContautofocusErrorOff: String = { return localize("orc_vuforia_menu_contautofocus_error_off", comment: "") }()
let kLocaleOrcVuforiaMenuDatasets: String = { return localize("orc_vuforia_menu_datasets", comment: "") }()
let kLocaleOrcVuforiaMenuCamera: String = { return localize("orc_vuforia_menu_camera", comment: "") }()
let kLocaleOrcVuforiaMenuCameraFront: String = { return localize("orc_vuforia_menu_camera_front", comment: "") }()
let kLocaleOrcVuforiaMenuCameraBack: String = { return localize("orc_vuforia_menu_camera_back", comment: "") }()
let kLocaleOrcVuforiaMenuButtonRed: String = { return localize("orc_vuforia_menu_button_red", comment: "") }()
let kLocaleOrcVuforiaMenuButtonBlue: String = { return localize("orc_vuforia_menu_button_blue", comment: "") }()
let kLocaleOrcVuforiaMenuButtonYellow: String = { return localize("orc_vuforia_menu_button_yellow", comment: "") }()
let kLocaleOrcVuforiaMenuButtonGreen: String = { return localize("orc_vuforia_menu_button_green", comment: "") }()
let kLocaleOrcVuforiaSplashScreenDescription: String = { return localize("orc_vuforia_splash_screen_description", comment: "") }()
let kLocaleOrcVuforiaErrorMissingVuforiaCredentials: String = { return localize("orc_vuforia_error_missing_vuforia_credentials", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorAuthorizationFailedTitle: String = { return localize("orc_vuforia_update_error_authorization_failed_title", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorProjectSuspendedTitle: String = { return localize("orc_vuforia_update_error_project_suspended_title", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorNoNetworkConnectionTitle: String = { return localize("orc_vuforia_update_error_no_network_connection_title", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorServiceNotAvailableTitle: String = { return localize("orc_vuforia_update_error_service_not_available_title", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorUpdateSdkTitle: String = { return localize("orc_vuforia_update_error_update_sdk_title", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorTimestampOutOfRangeTitle: String = { return localize("orc_vuforia_update_error_timestamp_out_of_range_title", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorRequestTimeoutTitle: String = { return localize("orc_vuforia_update_error_request_timeout_title", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorBadFrameQualityTitle: String = { return localize("orc_vuforia_update_error_bad_frame_quality_title", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorUnknownTitle: String = { return localize("orc_vuforia_update_error_unknown_title", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorAuthorizationFailedDesc: String = { return localize("orc_vuforia_update_error_authorization_failed_desc", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorProjectSuspendedDesc: String = { return localize("orc_vuforia_update_error_project_suspended_desc", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorNoNetworkConnectionDesc: String = { return localize("orc_vuforia_update_error_no_network_connection_desc", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorServiceNotAvailableDesc: String = { return localize("orc_vuforia_update_error_service_not_available_desc", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorUpdateSdkDesc: String = { return localize("orc_vuforia_update_error_update_sdk_desc", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorTimestampOutOfRangeDesc: String = { return localize("orc_vuforia_update_error_timestamp_out_of_range_desc", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorRequestTimeoutDesc: String = { return localize("orc_vuforia_update_error_request_timeout_desc", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorBadFrameQualityDesc: String = { return localize("orc_vuforia_update_error_bad_frame_quality_desc", comment: "") }()
let kLocaleOrcVuforiaUpdateErrorUnknownDesc: String = { return localize("orc_vuforia_update_error_unknown_desc", comment: "") }()
