/* PASOS: Arrancar desde la ruta donde esta webpack.config.js y abrir consola y poner: npm start  */

window.Clipboard = require("../external/clipboard.js-master/dist/clipboard.min.js")
require("../font/listFonts.js")
require("./fontPositionZone.js")
require("./colorZone.js")
require("./images.js")
require("./eventColor.js")
require("./validations.js")
require("./textField.js")
require("./picker.js")
require("./datePicker.js")
require("./boolean.js")
require("./index.js")
require("./jsWeb.js")