osx_image: xcode9
language: objective-c
env:
  global:
  - FRAMEWORK_NAME=GIGLibrary
  - PROJECT=GIGLibrary
  - SCHEME=GIGLibrary
  - OS=11.0
  - DEVICE="iPhone 7"
script:
  - set -o pipefail && xcodebuild -project $PROJECT.xcodeproj -scheme $SCHEME -sdk iphonesimulator -destination "platform=iOS Simulator,OS=$OS,name=$DEVICE" test | xcpretty
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
deploy:
  provider: releases
  api_key:
    secure: C9YT59reHk0El/KIWkuPBeEtHJ6+2Mbe7zFbOl5PLM42lcNkcNxzvdO4qpkkBut7JSuUwtg89wJUChH/alcGmeuhs6iIdA7DQIgkw/ouc1NzaFYBUZZp9TD3phKnhgWg07Xkp6G//mFqFxNO7wUhMY1Hxdn78JZZGMOm9RG1KQ9fWCcldTLE8riczQIXSsEZaq9+elk39wb1L+va4kaROHGninvDbyql5sDYd5pTSu5vjhfdG2SRGDEdB4aTyWX2Mdn6sTV7bFsbjoUFbfjF7o7HZW8NJ97ry4USCqi2xpubvdW3zCKXLTy4ZmgmYVBVjtDbnyv/+oyhhdvM/MPXNe2CfgMhdULxezN1gh7Jf47yhtCFnVEFVjFiRRLheJT3v1Jr0Y1O3n4oI4PZ0wXqT5I0lUV+iJOrAnPZmI78xXFu2GN0sRQKWNQEiqkhbO5eXI80IT+jcgUz9uDB+/8Yr/Z7RzTugY1spL2e63oUtxGhCFZRgvYbkvlAWql5bLzQdV4TAwZp8bc1rN2MWeupHX8E17t4Pcen6/setwViCUD+LV2aFngXYHua2nedqLYSZQT0vMPqPBsUberwFxPD8jFA987JrGh5ussisQHvv0/sabdlyTemrT6jYr5JLhh4dhz0F4r8cb85a5f47UkOx4wIk2765yJP4hT6Iz7zucA=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: gigigoapps/gigigo-ios-lib
    tags: true
notifications:
  slack:
    secure: cNoOkMCD2HkWfCbNL7qC/f5M8Ujk/WuRDJgszIqGYXjWyxfezmt9iUOuXiq+0k5rSH37y/Qj6Cjr/4vQZrX81r2z7B+s5wqUwz2WlFzTn5OzdBVAaq3XLAfD9gEP9ih7kXdNU17GJYLNfyDlnCbJtIvJwtqyTRewuglxk3Z9qFIvJb1DCTZX/Z3caZLr3c5UXB36jsA3w0v4MyQ27gIzzpBs+gby10ZKKuFJ1huGn6ask+HWGHZLhNiFvdf8WapbsV5fuhwUxj3F7OIloG0adf2FNkYAbcSnLIWe+dYFWpX1zn+hnafDglETDNejRGGzpHfk+ggNbM/Qia8CjR00yC7eD/HxBK66BMYs033KRmmj2yZClg0TdHA0Jp4rFUAc3/FAYM37Bf66IL9484X1EqbeWa3j9aRuU5JIVmYRzVNcQo3saZu+SksKSXJlVkkcPCQ5IoyopN0UJsFTd6NU9fE6X3i4HtOBhdW4Rrm//L0KScj6LDJJg3Qqmz2m93I9MNGutbkVD23Fs1hRRZjPcoWLPAr7SJohhf8Yx5UvPLXB8qlDI4K0SSsM3na7sWHpayxLELZ4p1xvKqgZ/IniIEGXvR+CKZlVNkECHzkOVqHVcVcqohT3G3JoaU8S1olUfLQAfYD4pfSdTLjolzVU/JDJq9go7qd4yyt1aAIxUS8=
